os:
- linux
language: php
env:
  - XDEBUG_MODE=coverage
php:
- '8.0'
services:
- postgresql
cache:
  directories:
  - node_modules
  - vendor
before_install:
  - sudo apt-get -y install php-xdebug
before_script:
- cp .env.travis .env
- sudo psql -c 'create database mintegration;' -U postgres
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate:fresh
script:
  - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml --coverage-clover=coverage.xml
deploy:
  provider: heroku
  api_key:
    secure: RII313kU9JXqcpHak/T80oUybn31v1h+Oz/wDKs7CP7E9FPBuzxbOLvvpsw7BpXJHkaIclmtCxyikQZWrGOkQDO2QqrUnvNQHXJmFrsbW13e14WskZhtrMhEi5HyyNueH1xqhGxsOHDLzvw4Z0FPe/0ZAtxIYAh3ND9+e1oXwbyOGq6c7AfbA5koRPAZZDNDLRd+G4rBPq5ZImBLKGUCStW1Yk0M/1kgaPlu09MdXQ7EujRvD++Y0mfw8E+vMzopOOBdfaKCYpTbun1WzBSYYS27NLAc7B3UBivOm085o/huam3bcz1grPHmutVmhsIpyisFh0FR2qpdtzLIgBsh0V26XbU8YwDVUcaoKCUSK30lp7VZ7TW6KYirfm3fsEUxxIfJlpRvGivK2zNGg1qco90Ys9GR0w6iuZDASIBEFnVbTpmcCJy5Y01aVhk76tpYimM6fF9CnjQ4bj2LR3sjmNgCXPc72m7kqtfEqv2W5kqaGLnpPDRo0redmig/dh8cx91U4b+lqVexxyifoSWnk4S1FBCj1Lp+7PopxN4DzKtct6LZUAudk4cjURk+RpcXLN6nvs3klnwN58wcayGRN1G4bDaai9lLV+lp1QbeLYvuzYTg8dBDD3dvAurOskptEU79P63XcSF1V5UYuWOftBGAynKGCbC/r5lwLky5C1Q=
  app: mintegration
  on: main
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks: https://mintegration.herokuapp.com/hooks/travis-ci
